name: Deploy ExoList to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Step 2: Install Node & Firebase CLI
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 3: Save service account secret as JSON file
      - name: Save Firebase Service Account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACC }}" > service-account.json

      # Step 4: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
        run: |
          firebase deploy --only hosting
